travis:
  secure:
    BINSTAR_TOKEN: mhxxfbLK+2D21hBASKqiLXdheAc96VYUyAOeAZBQpGPAFnC57j+hsAy1b+lEIBFJdkIsmm4MBJB70KPFaIKN0WSXE/x6e6VfKOex5hKbqoD8rUbQ0La9a2KZyrWGy0V2gSO0cVKJl7pwQq3z+EBIYuqbPt2wEN+eHVewL17XdnIMDWVKEko8C0PZ5R9u3CYWg7LZ1+lB3UHFTcB4RTsoMT3i0H8kPPCWUNSBcIXpGHIs1L0to/qN87P78W4mVNhaPjDuiQj1Rmej11AaRECDiZqIc6oK0uBFAfW2rs3AyXq5r3UvnRROqx21JqQRonva/qAfU5gOKYpt/0X/QNH6+TxqD+ZEEvOQKF9hTZAqgF/8gmLUShdIfko5NbYrKMiMSPJ7yQCkuW5m00d+IcZst/sJ2QCk3ow79z6jPIho2JEMEkWfLACIxr/54l6RQX1zP+uMU7GkhwQhoP5KcEFClKBUdD9/u7cE3VAvHnXouVYkUKR3nFDKn2pcDiG0xNE/vC22b55qnzY8gb3mLl9EmTOpuoZVpcgmhNuPiwkdoc4FNw+Ib3Oo8jEtb0wcx+8YQNEBywR7KrH/Foa9UcBCqHMRPVobqR9hr+/I5IwSN+bQ7mAAFBfjAQLHcTYD/jNyYGDyvnyHf3rLqe1m7XZXtW8LQhJY9h9V8Ue54nNdjhA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
